### ISSUE TITLE
Error on UglifyJs build

### ISSUE THREAD

**Issue by carromeu** [renanbastos93/image-to-base64#10]
Hi team,

First, congrats for this lib! It's really useful.

I am using it with a VueJS and Webpack. In the moment of the "npm run build" occurs:

ERROR in static/js/1.833d0ac1ff25b9ddb113.js from UglifyJs
Unexpected token: operator (>) [./node_modules/image-to-base64/index.js:7,0][static/js/1.833d0ac1ff25b9ddb113.js:11389,30]

Any suggestion to fix?

**Comment by renanbastos93** [comment]
Hello dude,

I did think a form to correct situation, but I will has to improve this code. 
Do you be to want tester for me?

see ya

**Comment by renanbastos93** [comment]
Hey @carromeu,

Can you test for me, please?
 `npm install --save https://github.com/renanbastos93/image-to-base64.git`

Thanks a lot

**Comment by carromeu** [comment]
Hi @renanbastos93,

Thanks for fast response! So, for now the error persists. I uninstalled the NPM release package and add from GIT directly. Removed entire 'node_modules' folder and reinstall everthing. But error persists:

![image](https://user-images.githubusercontent.com/195660/45846074-cbadb080-bcf4-11e8-8ea1-ca704e2a59d4.png)

**Comment by renanbastos93** [comment]
Hi @carromeu ,

What's versions you using of js, ts, node. uglify?

**Comment by renanbastos93** [comment]
@carromeu , Do you testing new version?

**Comment by carromeu** [comment]
Hi @renanbastos93. Yes. Sorry for late feedback. Now it works fine! Thanks very much!!

**Comment by renanbastos93** [comment]
Nice, I am happy. Your re welcome.
See ya
