### ISSUE TITLE
No `.catch( (error) =>`   on 404

### ISSUE THREAD

**Issue by VladimirKalachikhin** [renanbastos93/image-to-base64#13]
Subj

and imageToBase64, no image2base64

**Comment by renanbastos93** [comment]
@VladimirKalachikhin,

Thanks a lot by tell-me.

Can you explain as simulate this error? 
I guess that was a problem of us document `README`, right?

see ya

**Comment by VladimirKalachikhin** [comment]
If server return 404 - I am expecting an error, not complete. I.e. .catch, not .then:
```
imageToBase64("file_not_exist.png")
    .then(
        (response) => {
        	console.log(response); // PCFET0NUWVBF... - base64 of server 404 response
    )
    .catch( 	// no fired!
        (error) => {
            console.log('Error: '+error); //Exepection error....
        }
    ) 
```

**Comment by renanbastos93** [comment]
Okay, but you using in NodeJS or browser?

**Comment by VladimirKalachikhin** [comment]
In browser.

**Comment by renanbastos93** [comment]
ok, in browser you must setting the path, example:

```js
imageToBase64("./file_not_exist.png").then(console.log).catch(console.log);
```

#### OR

```js
imageToBase64("https://yourdomain.com/images/JavaScript-logo.png").then(console.log).catch(console.log);
```

In browser you always using URL.

Do you understood?

see ya.

**Comment by VladimirKalachikhin** [comment]
Sorry for delay.

Ok, if file name begin from "http..." then the .catch are fired on 404. If not (even if the path present) - the .catch not fired on 404. Is it ok?

**Comment by renanbastos93** [comment]
No problem, please send to me one example, is important I comment for you: "This lib just accept `https` not using `http`", ok?

This case on web (run in browser)

**Comment by VladimirKalachikhin** [comment]
https://is.gd/97xypC
```
<!DOCTYPE html >
<html lang="ru">
<head>
   <LINK href="common.css" rel="stylesheet" type="text/css">
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <META http-equiv="Content-Script-Type" content="text/javascript">
   <title>This is a example of image-to-base64</title>
   <script src="image-to-base64.min.js"></script> 
</head>
<body>
<h1>Hello!</h1>
<p>
<img id='image1' src='test/nodejs.png'>
<img id='image2' src='http://mediatheque.rsl.ru/image-to-base64/test/nodejs.png'>

<script>
imageToBase64("http://mediatheque.rsl.ru/image-to-base64/test/nodejs.png")
.then(
    (response) => {
    	alert('1. This is responce ok. Result are '+response.length+'bytes length.');
    }
)
.catch(
    (error) => {
        alert('1. Error');
    }
)

imageToBase64("/image-to-base64/test/nodejs.png")
.then(
    (response) => {
    	alert('2. This is responce ok too. Result are '+response.length+'bytes length.');
    }
)
.catch(
    (error) => {
        alert('2. Error');
    }
)

imageToBase64("test/nodejs.png")
.then(
    (response) => {
    	alert('3. And this responce ok. Result are '+response.length+'bytes length.');
    }
)
.catch(
    (error) => {
        alert('3. Error');
    }
)

imageToBase64("http://mediatheque.rsl.ru/nodejs.png")
.then(
    (response) => {
    	alert('4. This request return 404, but .catch not fired and responce length '+response.length+'bytes.');
    }
)
.catch(
    (error) => {
        alert('4. Error');
    }
)

imageToBase64("mediatheque.rsl.ru/nodejs.png")
.then(
    (response) => {
    	alert('5. This request return 404, but .catch not fired and responce length '+response.length+'bytes.');
    }
)
.catch(
    (error) => {
        alert('5. Error');
    }
)
imageToBase64("/test/nodejs.png")
.then(
    (response) => {
    	alert('6. And this request return 404, and .catch not fired and responce length '+response.length+'bytes.');
    }
)
.catch(
    (error) => {
        alert('6. Error');
    }
)
</script>
</body>
</html>```

**Comment by VladimirKalachikhin** [comment]
Sorry, I don't understand.
The right image url is: "http://mediatheque.rsl.ru/image-to-base64/test/nodejs.png"
The "http://mediatheque.rsl.ru/test/nodejs.png" - is a sample a bad url, this produce 404 server response.

By link above You can see code in action, and see alert number and message. Messages appear not in the order of numbers, of course.

**Comment by renanbastos93** [comment]
No problem, my English is very bad.

Well,

This error occurs because this route (URL) that you try access don't exists in your application.
Your images they are inside path `image-to-base64`, understood?

I realized that you this using my images of example, do you need on your application put on all images and execute code with path.

**Comment by VladimirKalachikhin** [comment]
Yes. My case is generate the image file name, and retrieve file by this name. If file exist - display img, if not - do something. I want only one request to server for it.
On this case I do not have way to check "File not exist" situation.

**Comment by renanbastos93** [comment]
Nice, always that don't found file the lib will return a base64. We go improvement the treatment this errors, what do you think?

**Comment by VladimirKalachikhin** [comment]
I think that on any error should be run the .catch branch.

**Comment by renanbastos93** [comment]
Nice, I will create a issue with this treatments for be implemented. For as soon possible to be make.
