### ISSUE TITLE
Module can't be loaded

### ISSUE THREAD

**Issue by tonyguerreiro92** [renanbastos93/image-to-base64#16]
Could not find a declaration file for module 'image-to-base64'. '/PATH/image-to-base64/image-to-base64.min.js' implicitly has an 'any' type.
  Try `npm install @types/image-to-base64` if it exists or add a new declaration (.d.ts) file containing `declare module 'image-to-base64';` [7016]

**Comment by renanbastos93** [comment]
Hey,

you should install with command npm install --save image-to-base64.
I don't using TypeScript, so I never testing.
Can you to make this test to we attack the problems, for us resolve it?

see ya

**Comment by renanbastos93** [comment]
without interaction, closed.
