### ISSUE TITLE
Invalid base 64 string [Help Wanted]

### ISSUE THREAD

**Issue by morgothx** [renanbastos93/image-to-base64#18]
Hi, I convert an image to base 64, got the string and send it to a backend project in the backend I'm decoding the string with https://www.npmjs.com/package/base64-to-image but that doesn't work.

Looking into the code the string generated doesn't match this regular expresion

var matches = base64Str.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);

But I copy the string in https://www.base64decode.net/base64-image-decoder and got the image back

So can you please help me to understand why it's not working.
Thank you in advance

**Comment by renanbastos93** [comment]
hey @morgothx , Do you have questions? 
Why you closed issue, so was resolved?
