### ISSUE TITLE
Build fails in create-react-app

### ISSUE THREAD

**Issue by faahim** [renanbastos93/image-to-base64#2]
Hi there, thanks for this amazing library. It helped me a lot. I'm new to all this, So excuse me if this isn't something I should create an issue for. But this is whats happening:

I've installed the library using npm and it works flawlessly. But when I try to create a production build of my app using `npm run build` it fails with the following error.
![screenshot from 2018-02-09 16-43-10](https://user-images.githubusercontent.com/21854687/36024285-80dc835a-0db9-11e8-898a-554c71e1feb3.png)

The link mentioned leads to a section of react-react-app repo where the say:
![screenshot from 2018-02-09 16-53-20](https://user-images.githubusercontent.com/21854687/36024367-c1a8aa4e-0db9-11e8-8792-bc99b5d69ff8.png)

Sounds like they suggest that you transpile your code to ES5 code. Could you please look into it? Also, do you have any idea how I might ignore this so I can keep developing while it's being fixed?

Thanks for the hard work again! 😄

**Comment by renanbastos93** [comment]
Hello @faahim 

Thanks a lot, for the information. I'll fix it. Anyway my suggestion is you wait a few hours, or I can show you a way to fix this temporary.

see ya

**Comment by faahim** [comment]
Hi there! I managed to fix my problem by just extracting the index.js file in my /src folder.
I thought I'd need some of the other files also, but it works just fine. 😃 

Thanks again! 😄

**Comment by renanbastos93** [comment]
Wow, nice dude. I happy for help you. Anyway can count on me.

Close #2

see ya
