### ISSUE TITLE
is there way I can run it synchronously?

### ISSUE THREAD

**Issue by adamchenwei** [renanbastos93/image-to-base64#20]
a bit hard to think about when I run this inside a forEach loop for the file...

**Comment by renanbastos93** [comment]
Yes, follow the example below:
```js
((async () => {
    const image2base64 = require('image-to-base64');
    const paths = ["path/img1.jpg", "path/img2.jpg", "path/img3.jpg"];
    
    try{
        for (let i=0; i<paths.length; i++) {
            await image2base64(paths[i])
        }
    } catch(error) {
        console.log("Some error ==> ", error)
    }

})();
```
Do you understand @adamchenwei ?

**Comment by adamchenwei** [comment]
@renanbastos93 the problem I was trying to solve is I am saving these generated base64 string into another collection of data, so I want to do something ONLY after all the base64 conversion are ended. This likely won't help with it, as it still did not really give a clear indicator of "end" of loop... or maybe I am missing something, maybe specific line here indicate that?

For now though, I am using the good old length count to determine that...

**Comment by renanbastos93** [comment]
@adamchenwei 
Okay, you can to use `Promise.all`, because of this code return ever a promise.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

```js
const image2base64 = require('image-to-base64');
const paths = ["path/img1.jpg", "path/img2.jpg", "path/img3.jpg"];
const waitResolve = [];
for (let i=0; i<paths.length; i++) {
    waitResolve.push(image2base64(paths[i]));
}
Promise.all(waitResolve).then(console.log).catch(console.log);
```

**Comment by renanbastos93** [comment]
@adamchenwei Did you resolved your problem?

**Comment by adamchenwei** [comment]
@renanbastos93 thanks for the suggestion! it's really clever! Would use this to optimize the logic I currently have. Thank you so much!
