### ISSUE TITLE
Error message not meaningful

### ISSUE THREAD

**Issue by FabianPiconeDev** [renanbastos93/image-to-base64#22]
My error response of a failing conversion currently is: 

```
error: TypeError: Failed to fetch
    message: "Failed to fetch"
    stack: "TypeError: Failed to fetch"
```

It would be great to have more detailed error informations, such as response code and any security (cross origin) errors.

**Comment by renanbastos93** [comment]
How nice, I liked your suggestion. Can you give examples?

**Comment by anilv0001** [comment]
Access to fetch at 'http://abc.com' from origin 'https://xy.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I m getting this response please let know anything I m missing thanks

**Comment by rdimascio** [comment]
@anilv0001 the abc.com server does not allow cross origin access. If you're trying to make a GET request to an external domain, especially one that you don't control, I would highly recommend using a proxy.
