### ISSUE TITLE
Cors-Policy Error

### ISSUE THREAD

**Issue by anilv0001** [renanbastos93/image-to-base64#23]
Access to fetch at 'http://abc.com' from origin 'https://xy.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I m getting this response when using in web,  please let know anything I m missing thanks

**Comment by rdimascio** [comment]
You'll need to use a CORS proxy, such as https://cors-anywhere.herokuapp.com. I would recommend cloning and hosting yourself if you're using this in production.
