### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nirav5884** [renanbastos93/image-to-base64#24]
```
import imageToBase64 from 'image-to-base64';
or 
import { imageToBase64 } from 'image-to-base64';
...
imageToBase64(url) // you can also to use url
      .then(
                (response) => {
                  console.log(response);
                }
              )
              .catch(
                (error) => {
                  console.log(error);
                }
              );
```
Above code in Typescript throws lot of errors on compile. Even i tried adding the js file, but no help.
```
ERROR in ./node_modules/image-to-base64/image-to-base64.min.js
Module not found: Error: Can't resolve 'fs' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch'
ERROR in ./node_modules/node-fetch/lib/response.js
Module not found: Error: Can't resolve 'http' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch'
ERROR in ./node_modules/image-to-base64/image-to-base64.min.js
Module not found: Error: Can't resolve 'path' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch'
ERROR in ./node_modules/node-fetch/lib/body.js
Module not found: Error: Can't resolve 'stream' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'zlib' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\node-fetch'
```

**Comment by renanbastos93** [comment]
Hello,

Can you install lib `node-fetch` to test again?


att

**Comment by nirav5884** [comment]
> Hello,
> 
> Can you install lib `node-fetch` to test again?
> 
> att

Not working, getting more errors 

`ERROR in ./node_modules/image-to-base64/image-to-base64.min.js
Module not found: Error: Can't resolve 'fs' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/lib/response.js
Module not found: Error: Can't resolve 'http' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch\lib'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch'
ERROR in ./node_modules/image-to-base64/image-to-base64.min.js
Module not found: Error: Can't resolve 'path' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/lib/body.js
Module not found: Error: Can't resolve 'stream' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch\lib'
ERROR in ./node_modules/image-to-base64/node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'zlib' in 'C:\Dev\ROM\Development\src\RomCloud\RomCloud.Web.UI\node_modules\image-to-base64\node_modules\node-fetch'`

**Comment by renanbastos93** [comment]
Do you use typescript at web, right?

**Comment by nirav5884** [comment]
Yes, Typescript in Web.

**Comment by renanbastos93** [comment]
When I developed this lib I focus on Node JS and web, without TypeScript. Maybe we can improve to create support for TS. Can you contribute? Just add this support and open a Pull Request.
