### ISSUE TITLE
how to solve ERR_UNESCAPED_CHARACTERS error?

### ISSUE THREAD

**Issue by ttiras** [renanbastos93/image-to-base64#29]
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:139:13)
    at request (https.js:309:10)
    at /usr/src/app/node_modules/image-to-base64/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/usr/src/app/node_modules/image-to-base64/node_modules/node-fetch/index.js:49:9)
    at Fetch (/usr/src/app/node_modules/image-to-base64/node_modules/node-fetch/index.js:37:10)
    at imageToBase64 (/usr/src/app/node_modules/image-to-base64/image-to-base64.min.js:1:643)
    at /usr/src/app/handlers/emails.js:91:36
    at Array.map (<anonymous>)
    at handler (/usr/src/app/handlers/emails.js:87:33) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
is this related to image names? images are reachable online.

**Comment by renanbastos93** [comment]
your error way line `/usr/src/app/handlers/emails.js:87:33`
Can you show name uses? Please, post here code from example.

**Comment by ttiras** [comment]
const items = order_items.map(async item=>{
        const price = (item.product.price - (item.product.price*item.product.discount/100))
        const image = `https://backend.rover.micota.com.tr/build/img/${item.product.image[0].path}.jpeg`

        const decodedImage = await imageToBase64(image)
          
        return (
         `<div style="border-style: solid">
         <img style="width:150px" src="data:image/jpg;base64,${decodedImage}">            
          <p><span>${item.product.name}</span></p>
          <p><span>${item.qty} Adet</span></p>
          <p><span>${price} TL</span></p>
          </div>`
        )                 
      })

**Comment by renanbastos93** [comment]
I tested it and worked well, but I made a code a little different.
Why I change it? `because I see one point`
> you don't treat `item.product.image` length


```js
var order_items = [
    {
        product: {
            name: "test",
            price: 1,
            discount: 0,
            image: [{
                path: "Supla_Beyaz1"
            }]
        },
        qty: 1
    }
]

let items = order_items.map(async item=>{
    let price = (item.product.price - (item.product.price*item.product.discount/100))
    let image = "";
    let decodedImage = "";

    if (item.product.image.length > 0 && item.product.image[0].path) {
        image = `https://backend.rover.micota.com.tr/build/img/${item.product.image[0].path}.jpeg`
    }

    decodedImage = await imageToBase64(image)
        
    return `<div style="border-style: solid">
        <img style="width:150px" src="data:image/jpg;base64,${decodedImage}">            
        <p><span>${item.product.name}</span></p>
        <p><span>${item.qty} Adet</span></p>
        <p><span>${price} TL</span></p>
    </div>`
})
```

Output:
![image](https://user-images.githubusercontent.com/8202898/87584047-46f30a00-c6b3-11ea-9aea-3bd4f201fabe.png)

**Comment by ttiras** [comment]
thank you very much. 
you are right, but i am sure that image is there because this endpoint is only posted with a product being present and every product has an image. 
so your code doesn't make a difference. my code worked for months, it only gave this error this morning and now it is working again and i don't know what happened and how it started working again. 

now i am afraid if it is going to give this error again in the future: code: 'ERR_UNESCAPED_CHARACTERS'
do you know what is this error about?

**Comment by renanbastos93** [comment]
@ttiras 

wow, so this problem `ERR_UNESCAPED_CHARACTERS` normally raises when to try request a URL with spaces then you must escape it ` or unsupported file extension.` 

> https://nodejs.org/api/errors.html#errors_err_unescaped_characters

**Comment by ttiras** [comment]
thank you renanbastos93,
actually there is no space in the urls but i will look into it. 
apparently the issue is not related to image-to-base64.
