### ISSUE TITLE
should work with react

### ISSUE THREAD

**Issue by renanbastos93** [renanbastos93/image-to-base64#3]
Stated that using it dons't as should with reactjs. So, we need implemention some bugfix.

**Comment by michelgomessilva** [comment]
I did not understand what error occurs! Do you have a description of this issue?

**Comment by renanbastos93** [comment]
Wow, I'm sorry, my english is very bad. I'll try explain it.

When you try make a project with react. It's occur this error "build fails", bellow has image about bug.

![image](https://user-images.githubusercontent.com/8202898/36929412-f8c88376-1e6e-11e8-8145-f373a5426403.png)
Other image, to auxiliary

![image](https://user-images.githubusercontent.com/8202898/36929416-02d60d02-1e6f-11e8-8b32-f4274c81eaa4.png)

This was create starting of **[ISSUE](https://github.com/renanbastos93/image-to-base64/issues/2)**

see ya
