### ISSUE TITLE
e.buffer is not a function

### ISSUE THREAD

**Issue by sedhalsoni** [renanbastos93/image-to-base64#37]
Getting Error in convert image url to base64.
> e.buffer is not a function

**Comment by renanbastos93** [comment]
@sedhalsoni 

Hi, thanks a lot to report for us

Can you show details about it?
* show traceback
* show the code that occurrent it
* node version
* using in browser/ server side

**Comment by renanbastos93** [comment]
Closed due to lack of information.

**Comment by IlyaZolotarev** [comment]
Hi! I have the same error.  What it can be?

![image](https://user-images.githubusercontent.com/40018150/90509300-c87e0200-e161-11ea-9c5f-55088d133fd7.png)

**Comment by IlyaZolotarev** [comment]
> Hi! I have the same error. What it can be?
> 
> ![image](https://user-images.githubusercontent.com/40018150/90509300-c87e0200-e161-11ea-9c5f-55088d133fd7.png)
> 
> in console I see :
> ![image](https://user-images.githubusercontent.com/40018150/90509441-fe22eb00-e161-11ea-9270-267e804019bc.png)

I deleted version 2.1.0 and installed 2.0.1 - This resolved my problem :)

**Comment by carromeu** [comment]
Same here. I downgrade to 2.0.1, like sugested by @IlyaZolotarev, but now has "2 low severity vulnerabilities" warning in my code.

**Comment by renanbastos93** [comment]
Reopen: Can we talk about it? 
@carromeu What are these vulnerabilities?
@IlyaZolotarev Did it happen on the web?

**Comment by carromeu** [comment]
@renanbastos93, version **2.0.1** in ```npm audit``` showing this report:

```
# npm audit report

node-fetch  <=2.6.0 || 3.0.0-beta.1 - 3.0.0-beta.8
Denial of Service - https://npmjs.com/advisories/1556
fix available via `npm audit fix --force`
Will install image-to-base64@2.1.1, which is outside the stated dependency range
node_modules/node-fetch
  image-to-base64  <=2.1.0
  Depends on vulnerable versions of node-fetch
  node_modules/image-to-base64

2 low severity vulnerabilities
```

**Comment by IlyaZolotarev** [comment]
> Reopen: Can we talk about it?
> @carromeu What are these vulnerabilities?
> @IlyaZolotarev Did it happen on the web?

Yes, it was on web

**Comment by renanbastos93** [comment]
Does someone want to open a pull request to fixes it?
