### ISSUE TITLE
How to return the Base64 from object imageToBase64

### ISSUE THREAD

**Issue by mohammad-saber** [renanbastos93/image-to-base64#40]
Thank you very much for sharing your code. I tested the sample code in Readme and I can see the results in console "console.log(response)". 

But, I would like to save Base64 into a variable and returns it. I need to use the Base64 in another function for further processing. I tried the following code. I want to save Base64 into variable image_base64:

```
const imageToBase64 = require('image-to-base64');

imageToBase64("1.jpg") // Path to the image
    .then(
        (response) => {
            //console.log(response)
            var image_base64 = response; // response is Base64
            return image_base64
        }
    )
    .catch(
        (error) => {
            console.log(error); // Logs an error if there was one
        }
    )
console.log(typeof image_base64)
```

The command "console.log(typeof image_base64)" prints "undefined". 

Could you please let me know me how to return Base64 from imageToBase64()?
Thank you very much.

**Comment by renanbastos93** [comment]
@mohammad-saber heyy
I'm sorry for making you wait

well, first you to understand more about promises using nodejs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

I will show you my code based on your e.g

```js
const imageToBase64 = require('image-to-base64');

var img1 = imageToBase64("1.jpg") // Path to the image
    .then(
        (response) => {
            //console.log(response)
            var image_base64 = response; // response is Base64
            return image_base64
        }
    )
    .catch(
        (error) => {
            console.log(error); // Logs an error if there was one
        }
    )
img.then(console.log)
```

you can to use also async/await treatment promises in nodejs

```js
async myImg(img){
    try {
        return imageToBase64("1.jpg");
    } catch(error) {
        throw error;
    }
}
console.log(myImg("1.jpg"))
```
