### ISSUE TITLE
statSync issue due to too large image size

### ISSUE THREAD

**Issue by razi0s** [renanbastos93/image-to-base64#48]
Hi, 

.png from 7 kb is working correctly, but the one from 12kb is not working and giving .statSync errors.
All the other sizes above at least 12kb are not working, and everything below max 7kb is working.

**Comment by renanbastos93** [comment]
> Hi,
> 
> .png from 7 kb is working correctly, but the one from 12kb is not working and giving .statSync errors.
> All the other sizes above at least 12kb are not working, and everything below max 7kb is working.

@razi0s Hi, how are you?
Can you share the error?

**Comment by jjnanthakumar** [comment]
![image](https://user-images.githubusercontent.com/46053893/112349903-22920780-8cef-11eb-9a14-7d4856e74fca.png)

**Comment by renanbastos93** [comment]
Can you share your code too?

**Comment by jjnanthakumar** [comment]
Sure!

```
const getBase64_custom=async (url)=>{
        var base64=await imageToBase(url);
        return base64
    }
```
The above function will return base64 from image url

Here is the sample image url:

https://images.news18.com/ibnlive/uploads/2019/05/PM-Narendra-Modi-flashes-the-victory-sign.jpg

**Comment by renanbastos93** [comment]
cool, do you use lib on nodejs or react, angular, vanillajs?

**Comment by jjnanthakumar** [comment]
I am just using it in frontend (ReactJs) 

https://www.npmjs.com/package/image-to-base64

**Comment by renanbastos93** [comment]
> I am just using it in frontend (ReactJs)
> 
> https://www.npmjs.com/package/image-to-base64

https://github.com/renanbastos93/image-to-base64/issues/2

this bug is know

**Comment by renanbastos93** [comment]
Can you try to repair it?

**Comment by jjnanthakumar** [comment]
You mean is that the issue in create-react-app?
I need to do as mentioned in #2 but no problem there are many other ways to convert from url to base64 like axios etc.
Thanks for your help :)
