### ISSUE TITLE
don't have time to take care of him, Can someone take care of it?

### ISSUE THREAD

**Issue by renanbastos93** [renanbastos93/image-to-base64#51]
I am thinking to deprecate this library, some organizations or peoples wishes to take care of it?

**Comment by legend80s** [comment]
I can take care of it. my https://www.npmjs.com/package/tinify-client depends image-to-base64.

**Comment by renanbastos93** [comment]
how cool, What do you think we create a org to keeping those projects?

**Comment by legend80s** [comment]
okay
