### ISSUE TITLE
invalid regular expression in safari

### ISSUE THREAD

**Issue by jan-bogaerts** [renanbastos93/image-to-base64#53]
https://github.com/renanbastos93/image-to-base64/blob/be695c53d656529b59068d83878f184c14654c70/image-to-base64.js#L8

This line gives a problem in safari: invalid group specifier name.
apparently something to do with this:
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by renanbastos93** [comment]
@jan-bogaerts 
🤕 Oh nooo, Do you have an idea? Let's go to improve it together?

**Comment by tomtapia** [comment]
Hi Renan,

I tested the regular expression with this site https://regex101.com/ then I received an error.
![image](https://user-images.githubusercontent.com/419426/109971326-e1e93480-7cd4-11eb-9517-b30b65640c2b.png)
If you escape delimiter should be work fine.

Cheers!!!

**Comment by renanbastos93** [comment]
> Hi Renan,
> 
> I tested the regular expression with this site https://regex101.com/ then I received an error.
> ![image](https://user-images.githubusercontent.com/419426/109971326-e1e93480-7cd4-11eb-9517-b30b65640c2b.png)
> If you escape delimiter should be work fine.
> 
> Cheers!!!

Hi @tomtapia ,

Well, what version are you using?

**Comment by tomtapia** [comment]
> > Hi Renan,
> > I tested the regular expression with this site https://regex101.com/ then I received an error.
> > ![image](https://user-images.githubusercontent.com/419426/109971326-e1e93480-7cd4-11eb-9517-b30b65640c2b.png)
> > If you escape delimiter should be work fine.
> > Cheers!!!
> 
> Hi @tomtapia ,
> 
> Well, what version are you using?

I'm using "image-to-base64": "^2.1.1" from NPM repository.

**Comment by renanbastos93** [comment]
wow, thanks.
![image](https://user-images.githubusercontent.com/8202898/110050018-c102fc80-7d31-11eb-915f-f60e2e394900.png)

I tested using this regex on `regex101` ant it was successful.

**Comment by tomtapia** [comment]
Yeah!!! You're right, it was my mistake. I'll keep trying to make this module work with my code.

Thanks a lot for your help. 👍
