### ISSUE TITLE
Cannot find module 'fs' in 'image-to-base64'

### ISSUE THREAD

**Issue by estevaosa** [renanbastos93/image-to-base64#67]
I am using the Wix, and I am facing this problem "Cannot find module 'fs' in 'image-to-base64'". THe version of the library is 2.1.1. Do you know the solution for it in Wix?

Thanks

**Comment by renanbastos93** [comment]
Hi dude, can you show me an example of your code?
Do you import correctly the library?

**Comment by estevaosa** [comment]
Hi Renan, 

Here is the code:
`import { imageToBase64 } from 'image-to-base64';

const url = 'https://static.wixstatic.com/media/1556ff_6196319be99f48be9def6d8685176a1c~mv2.png'
		imageToBase64(url) // Path to the image
		.then(
			(response) => {
				console.log(response); // "cGF0aC90by9maWxlLmpwZw=="
			}
		)
		.catch(
			(error) => {
				console.log(error); // Logs an error if there was one
			}
		)

`


![image](https://user-images.githubusercontent.com/12243415/104186653-7af68000-53f5-11eb-9c5a-d97a1bcebef3.png)

Is there some mistake?

**Comment by renanbastos93** [comment]
> Hi Renan,
> 
> Here is the code:
> `import { imageToBase64 } from 'image-to-base64';
> 
> const url = 'https://static.wixstatic.com/media/1556ff_6196319be99f48be9def6d8685176a1c~mv2.png'
> imageToBase64(url) // Path to the image
> .then(
> (response) => {
> console.log(response); // "cGF0aC90by9maWxlLmpwZw=="
> }
> )
> .catch(
> (error) => {
> console.log(error); // Logs an error if there was one
> }
> )
> 
> `
> 
> ![image](https://user-images.githubusercontent.com/12243415/104186653-7af68000-53f5-11eb-9c5a-d97a1bcebef3.png)
> 
> Is there some mistake?

What is the version to use? WIX use react?

**Comment by estevaosa** [comment]
Renan, now it works.

I just change the way to import the library. I used as the recommendation of the documentation. 
`const imageToBase64 = require('image-to-base64');

The Wix show a mistake in the editor when import the library using "require". Actually there is no error, it works perfectly.

![image](https://user-images.githubusercontent.com/12243415/104236004-946aec80-5434-11eb-8c2a-69556be7f29b.png)

Thank you very much for the help!
