### ISSUE TITLE
What should to be validate?

### ISSUE THREAD

**Issue by robsongajunior** [renanbastos93/image-to-base64#7]
# DESCRIPTION

https://github.com/renanbastos93/image-to-base64/blob/master/index.js#L14

The pointed line is not doing what should did.

**Comment by renanbastos93** [comment]
I had not noticed, but this is a bug.
Can you wish to tidy up?

You must change `if(valid !== true){` for `if(valid.test(param) !== true){` because we am validate one regex.

**Comment by renanbastos93** [comment]
This bug was fixed.
Thanks
