### ISSUE TITLE
CORS error when using imageToBase64

### ISSUE THREAD

**Issue by jasonnn0210** [renanbastos93/image-to-base64#75]
How do I disable the CORS header in the request? When I run the code below, I get a CORS error.

```
        imageToBase64('<image_url>') // Image URL
            .then((response) => {
                console.log(response);
                doc.addImage(response, 'JPEG', width / 2, 650, 400, 125);
            }
            )
            .catch((error) => {
                console.log(error); // Logs an error if there was one
            }
            )
```

`Access to fetch at '<image_url>' from origin '<mywebpage>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Help please, thank you!

**Comment by renanbastos93** [comment]
> How do I disable the CORS header in the request? When I run the code below, I get a CORS error.
> 
> ```
>         imageToBase64('<image_url>') // Image URL
>             .then((response) => {
>                 console.log(response);
>                 doc.addImage(response, 'JPEG', width / 2, 650, 400, 125);
>             }
>             )
>             .catch((error) => {
>                 console.log(error); // Logs an error if there was one
>             }
>             )
> ```
> 
> `Access to fetch at '<image_url>' from origin '<mywebpage>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> Help please, thank you!

Hi @jasonnn0210 
How's it goin'?


well, it is problem for CORS yet, so we need to open CORS in your API.
