### ISSUE TITLE
import image, and added to my backgound-image, but shows a little square

### ISSUE THREAD

**Issue by pedropcruz** [renanbastos93/image-to-base64#8]
Hello everyone,

Well the problem it's on my react app, i'm using styled-components to style my components, and i am doing this:

```
import styled from 'styled-components'
import image from '../resources/img/img.png';

const CSS = styled.section`
background-image: url(${image});
`
```

actually webpack changed this, but the characters are to small to create the entire image:

he replicates this:

```
background-image: url(data:image/png;charset=utf-8;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJzdGF0aWMvbWVkaWEvYmdub3VzYWl3ZWJzaXRlLjdjZTQ4NzU0LnBuZyI7)
```

EDIT: and this is the source page of this data-uri:

```
module.exports = __webpack_public_path__ + "static/media/bgnousaiwebsite.7ce48754.png";
```

**Comment by renanbastos93** [comment]
Hello,
How are you?

So, I understand very little of reactjs, I'll speak with my friends to think a solution. Okay? 
If you want explain more, will be better for help you.

see ya.

**Comment by renanbastos93** [comment]
Hey @pedropcruz  ,

I fixed problem, but I want see with. 
Can you test for me, please?

Realize test
 `npm install --save https://github.com/renanbastos93/image-to-base64.git`

Thanks a lot
