### ISSUE TITLE
'fs' module

### ISSUE THREAD

**Issue by makhnnar** [renanbastos93/image-to-base64#9]
error: bundling failed: Error: While trying to resolve module `fs` from file `D:
\otto-mobile\node_modules\image-to-base64\index.js`, the package `D:\otto-mobile
\node_modules\fs\package.json` was successfully found. However, this package its
elf specifies a `main` module field that could not be resolved (`D:\otto-mobile\
node_modules\fs\index.js`. Indeed, none of these files exist:

  * `D:\otto-mobile\node_modules\fs\index.js(.native||.android.js|.native.js|.js
|.android.json|.native.json|.json)`
  * `D:\otto-mobile\node_modules\fs\index.js\index(.native||.android.js|.native.
js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (D:\otto-mobile\node_modules\metro\sr
c\node-haste\DependencyGraph\ResolutionRequest.js:103:15)
    at DependencyGraph.resolveDependency (D:\otto-mobile\node_modules\metro\src\
node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (D:\otto-mobile\node_modules\metro\src\Delt
aBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (D:\otto-mobile\node_modules\metro\src\DeltaBundler\t
raverseDependencies.js:374:16)
    at D:\otto-mobile\node_modules\metro\src\DeltaBundler\traverseDependencies.j
s:212:33
    at Generator.next (<anonymous>)
    at step (D:\otto-mobile\node_modules\metro\src\DeltaBundler\traverseDependen
cies.js:297:313)
    at D:\otto-mobile\node_modules\metro\src\DeltaBundler\traverseDependencies.j
s:297:473
    at <anonymous>

This problem appears when i try to use this dependency in a react native project. It makes the compilation impossible

**Comment by renanbastos93** [comment]
Hello @makhnnar 

I was reading a others problem similar, and everybody recommend execute some type `rm ./node_modules/react-native/local-cli/core/fixtures/files/package.json`

Also I want know what's version of react, nodejs and npm.

Thanks, see ya

**Comment by makhnnar** [comment]
"react": "16.3.1",
"node": "8.11.1"
"npm": "5.6.0"

**Comment by renanbastos93** [comment]
Thanks,
Did you try to do what I said?

**Comment by renanbastos93** [comment]
Hey @makhnnar ,

I fixed problem, but I want see with. 
Can you test for me, please?

Realize test
 `npm install --save https://github.com/renanbastos93/image-to-base64.git`

Thanks a lot
